# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('iata', models.CharField(blank=True, max_length=50, null=True)),
                ('icao', models.CharField(blank=True, max_length=50, null=True)),
                ('callsign', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.CharField(max_length=1)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, null=True)),
                ('icao', models.CharField(max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('offset', models.FloatField(blank=True, null=True)),
                ('dst', models.CharField(blank=True, max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_utc', models.DateTimeField(verbose_name='Departure Time (UTC)')),
                ('arrive_utc', models.DateTimeField(verbose_name='Arrival Time (UTC)')),
            ],
            options={
                'ordering': ('route', 'depart_utc'),
            },
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ECON', 'Economy'), ('SCND', 'Second'), ('BSNS', 'Business'), ('FRST', 'First')], max_length=4)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Flight Classes',
                'ordering': ('aircraft', '-capacity'),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('line', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('dest', models.TextField(blank=True, null=True)),
                ('codeshare', models.CharField(blank=True, max_length=50, null=True)),
                ('stops', models.PositiveIntegerField(blank=True, null=True)),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('origin', 'destination'),
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('flight', 'seat', 'customer'),
            },
        ),
    ]
