# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 19:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('air', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='air.Flight'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='air.Seat'),
        ),
        migrations.AddField(
            model_name='seat',
            name='flight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='air.FlightClass'),
        ),
        migrations.AddField(
            model_name='route',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='air.Airline'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_arriving', to='air.Airport'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routes_departing', to='air.Airport'),
        ),
        migrations.AddField(
            model_name='flightclass',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flight_classes', to='air.Aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='air.Aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='air.Route'),
        ),
    ]
