# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_auto_20181017_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='iata',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='icao',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='icao',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='route',
            name='codeshare',
        ),
        migrations.RemoveField(
            model_name='route',
            name='dest',
        ),
        migrations.RemoveField(
            model_name='route',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='route',
            name='line',
        ),
        migrations.RemoveField(
            model_name='route',
            name='source',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
    ]
