# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0003_auto_20181017_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='active',
            field=models.BooleanField(),
        ),
    ]
