# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0005_auto_20181017_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
