# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0006_airline_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
