# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0007_route_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('airline', 'origin', 'destination')},
        ),
    ]
