# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0010_auto_20181019_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ('airline__code', 'number')},
        ),
        migrations.AddField(
            model_name='seat',
            name='aisle',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='window',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
