# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0014_auto_20181021_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([('flight', 'seat')]),
        ),
    ]
