# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0015_auto_20181021_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
