# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0017_auto_20181023_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
