# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0018_auto_20181023_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(null=True),
        ),
    ]
