# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0019_auto_20181023_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='ctry',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='air.Country'),
        ),
    ]
