# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0020_auto_20181023_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='ctry',
        ),
    ]
