# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0022_auto_20181023_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightclass',
            options={'ordering': ('flight', '-capacity'), 'verbose_name_plural': 'Flight Classes'},
        ),
        migrations.RemoveField(
            model_name='flightclass',
            name='aircraft',
        ),
        migrations.AddField(
            model_name='flightclass',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='flight_classes', to='air.Flight'),
            preserve_default=False,
        ),
    ]
