# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0023_auto_20181024_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ('flight_class__flight__aircraft__name', 'flight_class__name', 'code')},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('seat', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
    ]
