# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0024_auto_20181024_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='air.Seat'),
        ),
    ]
