# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('name',), 'verbose_name': 'User'},
        ),
    ]
